# Generated by Django 4.2.8 on 2023-12-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='Departments',
        ),
    ]
