# Generated by Django 4.2.8 on 2023-12-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_department_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('address', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('course', models.TextField(max_length=250, unique=True)),
                ('gender', models.TextField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('DOB', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
