# Generated by Django 4.2.8 on 2023-12-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_alter_profiles_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='course',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
