# Generated by Django 4.2.8 on 2023-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_profiles_course_alter_profiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='department',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
